// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-contacts.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contacts_default = defineTool({
  name: "list_contacts",
  title: "List contacts",
  description: "List contacts saved in Aponjon for the signed-in admin. Returns up to `limit` contacts ordered by most recently created.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max rows to return (1-100)."),
    category: z.string().optional().describe("Optional category filter (e.g. \u09AA\u09B0\u09BF\u09AC\u09BE\u09B0, \u09AC\u09A8\u09CD\u09A7\u09C1).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client(ctx).from("contacts").select("id,name,phone,category,custom_category,note,created_at").order("created_at", { ascending: false }).limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { contacts: data }
    };
  }
});

// src/lib/mcp/tools/search-contacts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_contacts_default = defineTool2({
  name: "search_contacts",
  title: "Search contacts",
  description: "Search Aponjon contacts by name, phone number, or note text. Case-insensitive partial match.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Text to search for in name, phone, or note."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const safe = query.replace(/[%,]/g, " ");
    const { data, error } = await client2(ctx).from("contacts").select("id,name,phone,category,note,address,created_at").or(`name.ilike.%${safe}%,phone.ilike.%${safe}%,note.ilike.%${safe}%`).order("created_at", { ascending: false }).limit(limit);
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { results: data }
    };
  }
});

// src/lib/mcp/tools/get-contact.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_contact_default = defineTool3({
  name: "get_contact",
  title: "Get contact",
  description: "Fetch a single Aponjon contact's full details by its id.",
  inputSchema: {
    id: z3.string().uuid().describe("Contact UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await client3(ctx).from("contacts").select(
      "id,name,phone,whatsapp,imo,telegram,facebook,email,category,custom_category,note,address,blood_group,birthday,photo_url,created_at,updated_at"
    ).eq("id", id).maybeSingle();
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data)
      return { content: [{ type: "text", text: "Contact not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { contact: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zqfzihpxndkwitkwrpnp";
var mcp_default = defineMcp({
  name: "aponjon-mcp",
  title: "\u0986\u09AA\u09A8\u099C\u09A8 (Aponjon)",
  version: "0.1.0",
  instructions: "Tools for the Aponjon contact directory. Sign in as an admin to list, search, and inspect contacts stored in the app. All access is scoped by the signed-in user's row-level policies.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_contacts_default, search_contacts_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
